package com.scdeport.scdrive.speed

data class VehicleSpeedState(
    val rawGpsSpeedKmh: Double,
    val predictedSpeedKmh: Double,
    val estimatedSpeedKmh: Double,
    val displaySpeedKmh: Double,
    val accelerationMps2: Double,
    val forwardAccelerationMps2: Double,
    val gpsAccuracyM: Double,
    val gpsSpeedAccuracyMps: Double,
    val gpsConfidence: Double,
    val gpsAgeMs: Double,
    val gpsRateHz: Double,
    val imuRateHz: Double,
    val engineRateHz: Double,
    val rawAccelMps2: Double,
    val filterGain: Double,
    val state: String,
    val hasGpsFix: Boolean,
    val isGpsReliable: Boolean,
    val isStale: Boolean,
    val imuAvailable: Boolean,
    val imuCalibrated: Boolean,
    val latitude: Double,
    val longitude: Double,
    val headingDeg: Double,
    val emittedElapsedRealtimeNanos: Long,
    val nativeProcessingMs: Double,
    val logPath: String?,
) {
    fun toMap(): Map<String, Any?> = mapOf(
        "rawGpsSpeedKmh" to rawGpsSpeedKmh,
        "predictedSpeedKmh" to predictedSpeedKmh,
        "estimatedSpeedKmh" to estimatedSpeedKmh,
        "displaySpeedKmh" to displaySpeedKmh,
        "accelerationMps2" to accelerationMps2,
        "forwardAccelerationMps2" to forwardAccelerationMps2,
        "gpsAccuracyM" to gpsAccuracyM,
        "gpsSpeedAccuracyMps" to gpsSpeedAccuracyMps,
        "gpsConfidence" to gpsConfidence,
        "gpsAgeMs" to gpsAgeMs,
        "gpsRateHz" to gpsRateHz,
        "imuRateHz" to imuRateHz,
        "engineRateHz" to engineRateHz,
        "rawAccelMps2" to rawAccelMps2,
        "filterGain" to filterGain,
        "state" to state,
        "hasGpsFix" to hasGpsFix,
        "isGpsReliable" to isGpsReliable,
        "isStale" to isStale,
        "imuAvailable" to imuAvailable,
        "imuCalibrated" to imuCalibrated,
        "latitude" to latitude,
        "longitude" to longitude,
        "headingDeg" to headingDeg,
        "emittedElapsedRealtimeNanos" to emittedElapsedRealtimeNanos,
        "nativeProcessingMs" to nativeProcessingMs,
        "logPath" to logPath,
    )
}
